name: CI
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke
        run: |
          python - << 'PY'
          import importlib
          for m in ["streamlit","pandas","requests","pyarrow"]:
              importlib.import_module(m)
          print("OK")
          PY
